[project]
name = "odysya"
version = "0.1.0"
description = "Planner for Odysya"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "groq>=0.31.1",
    "logger>=1.4",
    "mcp>=1.13.1",
    "pydantic>=2.11.7",
]
